# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sezan92/MEGA/Work/C++/projects/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sezan92/MEGA/Work/C++/projects

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/local/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sezan92/MEGA/Work/C++/projects/CMakeFiles /home/sezan92/MEGA/Work/C++/projects/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sezan92/MEGA/Work/C++/projects/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Array

# Build rule for target.
Array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Array
.PHONY : Array

# fast build rule for target.
Array/fast:
	$(MAKE) -f CMakeFiles/Array.dir/build.make CMakeFiles/Array.dir/build
.PHONY : Array/fast

#=============================================================================
# Target rules for targets named Namespace

# Build rule for target.
Namespace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Namespace
.PHONY : Namespace

# fast build rule for target.
Namespace/fast:
	$(MAKE) -f CMakeFiles/Namespace.dir/build.make CMakeFiles/Namespace.dir/build
.PHONY : Namespace/fast

#=============================================================================
# Target rules for targets named Random

# Build rule for target.
Random: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Random
.PHONY : Random

# fast build rule for target.
Random/fast:
	$(MAKE) -f CMakeFiles/Random.dir/build.make CMakeFiles/Random.dir/build
.PHONY : Random/fast

#=============================================================================
# Target rules for targets named Trigon

# Build rule for target.
Trigon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Trigon
.PHONY : Trigon

# fast build rule for target.
Trigon/fast:
	$(MAKE) -f CMakeFiles/Trigon.dir/build.make CMakeFiles/Trigon.dir/build
.PHONY : Trigon/fast

#=============================================================================
# Target rules for targets named cbr

# Build rule for target.
cbr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cbr
.PHONY : cbr

# fast build rule for target.
cbr/fast:
	$(MAKE) -f CMakeFiles/cbr.dir/build.make CMakeFiles/cbr.dir/build
.PHONY : cbr/fast

#=============================================================================
# Target rules for targets named class

# Build rule for target.
class: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 class
.PHONY : class

# fast build rule for target.
class/fast:
	$(MAKE) -f CMakeFiles/class.dir/build.make CMakeFiles/class.dir/build
.PHONY : class/fast

#=============================================================================
# Target rules for targets named class_This

# Build rule for target.
class_This: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 class_This
.PHONY : class_This

# fast build rule for target.
class_This/fast:
	$(MAKE) -f CMakeFiles/class_This.dir/build.make CMakeFiles/class_This.dir/build
.PHONY : class_This/fast

#=============================================================================
# Target rules for targets named default_value

# Build rule for target.
default_value: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 default_value
.PHONY : default_value

# fast build rule for target.
default_value/fast:
	$(MAKE) -f CMakeFiles/default_value.dir/build.make CMakeFiles/default_value.dir/build
.PHONY : default_value/fast

#=============================================================================
# Target rules for targets named return_reference

# Build rule for target.
return_reference: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 return_reference
.PHONY : return_reference

# fast build rule for target.
return_reference/fast:
	$(MAKE) -f CMakeFiles/return_reference.dir/build.make CMakeFiles/return_reference.dir/build
.PHONY : return_reference/fast

#=============================================================================
# Target rules for targets named size

# Build rule for target.
size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 size
.PHONY : size

# fast build rule for target.
size/fast:
	$(MAKE) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/build
.PHONY : size/fast

#=============================================================================
# Target rules for targets named str

# Build rule for target.
str: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 str
.PHONY : str

# fast build rule for target.
str/fast:
	$(MAKE) -f CMakeFiles/str.dir/build.make CMakeFiles/str.dir/build
.PHONY : str/fast

#=============================================================================
# Target rules for targets named struct

# Build rule for target.
struct: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 struct
.PHONY : struct

# fast build rule for target.
struct/fast:
	$(MAKE) -f CMakeFiles/struct.dir/build.make CMakeFiles/struct.dir/build
.PHONY : struct/fast

Array.o: Array.cpp.o
.PHONY : Array.o

# target to build an object file
Array.cpp.o:
	$(MAKE) -f CMakeFiles/Array.dir/build.make CMakeFiles/Array.dir/Array.cpp.o
.PHONY : Array.cpp.o

Array.i: Array.cpp.i
.PHONY : Array.i

# target to preprocess a source file
Array.cpp.i:
	$(MAKE) -f CMakeFiles/Array.dir/build.make CMakeFiles/Array.dir/Array.cpp.i
.PHONY : Array.cpp.i

Array.s: Array.cpp.s
.PHONY : Array.s

# target to generate assembly for a file
Array.cpp.s:
	$(MAKE) -f CMakeFiles/Array.dir/build.make CMakeFiles/Array.dir/Array.cpp.s
.PHONY : Array.cpp.s

Call_by_reference.o: Call_by_reference.cpp.o
.PHONY : Call_by_reference.o

# target to build an object file
Call_by_reference.cpp.o:
	$(MAKE) -f CMakeFiles/cbr.dir/build.make CMakeFiles/cbr.dir/Call_by_reference.cpp.o
.PHONY : Call_by_reference.cpp.o

Call_by_reference.i: Call_by_reference.cpp.i
.PHONY : Call_by_reference.i

# target to preprocess a source file
Call_by_reference.cpp.i:
	$(MAKE) -f CMakeFiles/cbr.dir/build.make CMakeFiles/cbr.dir/Call_by_reference.cpp.i
.PHONY : Call_by_reference.cpp.i

Call_by_reference.s: Call_by_reference.cpp.s
.PHONY : Call_by_reference.s

# target to generate assembly for a file
Call_by_reference.cpp.s:
	$(MAKE) -f CMakeFiles/cbr.dir/build.make CMakeFiles/cbr.dir/Call_by_reference.cpp.s
.PHONY : Call_by_reference.cpp.s

Class.o: Class.cpp.o
.PHONY : Class.o

# target to build an object file
Class.cpp.o:
	$(MAKE) -f CMakeFiles/class.dir/build.make CMakeFiles/class.dir/Class.cpp.o
.PHONY : Class.cpp.o

Class.i: Class.cpp.i
.PHONY : Class.i

# target to preprocess a source file
Class.cpp.i:
	$(MAKE) -f CMakeFiles/class.dir/build.make CMakeFiles/class.dir/Class.cpp.i
.PHONY : Class.cpp.i

Class.s: Class.cpp.s
.PHONY : Class.s

# target to generate assembly for a file
Class.cpp.s:
	$(MAKE) -f CMakeFiles/class.dir/build.make CMakeFiles/class.dir/Class.cpp.s
.PHONY : Class.cpp.s

ClassWithThisPointer.o: ClassWithThisPointer.cpp.o
.PHONY : ClassWithThisPointer.o

# target to build an object file
ClassWithThisPointer.cpp.o:
	$(MAKE) -f CMakeFiles/class_This.dir/build.make CMakeFiles/class_This.dir/ClassWithThisPointer.cpp.o
.PHONY : ClassWithThisPointer.cpp.o

ClassWithThisPointer.i: ClassWithThisPointer.cpp.i
.PHONY : ClassWithThisPointer.i

# target to preprocess a source file
ClassWithThisPointer.cpp.i:
	$(MAKE) -f CMakeFiles/class_This.dir/build.make CMakeFiles/class_This.dir/ClassWithThisPointer.cpp.i
.PHONY : ClassWithThisPointer.cpp.i

ClassWithThisPointer.s: ClassWithThisPointer.cpp.s
.PHONY : ClassWithThisPointer.s

# target to generate assembly for a file
ClassWithThisPointer.cpp.s:
	$(MAKE) -f CMakeFiles/class_This.dir/build.make CMakeFiles/class_This.dir/ClassWithThisPointer.cpp.s
.PHONY : ClassWithThisPointer.cpp.s

Namespace.o: Namespace.cpp.o
.PHONY : Namespace.o

# target to build an object file
Namespace.cpp.o:
	$(MAKE) -f CMakeFiles/Namespace.dir/build.make CMakeFiles/Namespace.dir/Namespace.cpp.o
.PHONY : Namespace.cpp.o

Namespace.i: Namespace.cpp.i
.PHONY : Namespace.i

# target to preprocess a source file
Namespace.cpp.i:
	$(MAKE) -f CMakeFiles/Namespace.dir/build.make CMakeFiles/Namespace.dir/Namespace.cpp.i
.PHONY : Namespace.cpp.i

Namespace.s: Namespace.cpp.s
.PHONY : Namespace.s

# target to generate assembly for a file
Namespace.cpp.s:
	$(MAKE) -f CMakeFiles/Namespace.dir/build.make CMakeFiles/Namespace.dir/Namespace.cpp.s
.PHONY : Namespace.cpp.s

Random.o: Random.cpp.o
.PHONY : Random.o

# target to build an object file
Random.cpp.o:
	$(MAKE) -f CMakeFiles/Random.dir/build.make CMakeFiles/Random.dir/Random.cpp.o
.PHONY : Random.cpp.o

Random.i: Random.cpp.i
.PHONY : Random.i

# target to preprocess a source file
Random.cpp.i:
	$(MAKE) -f CMakeFiles/Random.dir/build.make CMakeFiles/Random.dir/Random.cpp.i
.PHONY : Random.cpp.i

Random.s: Random.cpp.s
.PHONY : Random.s

# target to generate assembly for a file
Random.cpp.s:
	$(MAKE) -f CMakeFiles/Random.dir/build.make CMakeFiles/Random.dir/Random.cpp.s
.PHONY : Random.cpp.s

Trigonometry.o: Trigonometry.cpp.o
.PHONY : Trigonometry.o

# target to build an object file
Trigonometry.cpp.o:
	$(MAKE) -f CMakeFiles/Trigon.dir/build.make CMakeFiles/Trigon.dir/Trigonometry.cpp.o
.PHONY : Trigonometry.cpp.o

Trigonometry.i: Trigonometry.cpp.i
.PHONY : Trigonometry.i

# target to preprocess a source file
Trigonometry.cpp.i:
	$(MAKE) -f CMakeFiles/Trigon.dir/build.make CMakeFiles/Trigon.dir/Trigonometry.cpp.i
.PHONY : Trigonometry.cpp.i

Trigonometry.s: Trigonometry.cpp.s
.PHONY : Trigonometry.s

# target to generate assembly for a file
Trigonometry.cpp.s:
	$(MAKE) -f CMakeFiles/Trigon.dir/build.make CMakeFiles/Trigon.dir/Trigonometry.cpp.s
.PHONY : Trigonometry.cpp.s

default_function_value_variable.o: default_function_value_variable.cpp.o
.PHONY : default_function_value_variable.o

# target to build an object file
default_function_value_variable.cpp.o:
	$(MAKE) -f CMakeFiles/default_value.dir/build.make CMakeFiles/default_value.dir/default_function_value_variable.cpp.o
.PHONY : default_function_value_variable.cpp.o

default_function_value_variable.i: default_function_value_variable.cpp.i
.PHONY : default_function_value_variable.i

# target to preprocess a source file
default_function_value_variable.cpp.i:
	$(MAKE) -f CMakeFiles/default_value.dir/build.make CMakeFiles/default_value.dir/default_function_value_variable.cpp.i
.PHONY : default_function_value_variable.cpp.i

default_function_value_variable.s: default_function_value_variable.cpp.s
.PHONY : default_function_value_variable.s

# target to generate assembly for a file
default_function_value_variable.cpp.s:
	$(MAKE) -f CMakeFiles/default_value.dir/build.make CMakeFiles/default_value.dir/default_function_value_variable.cpp.s
.PHONY : default_function_value_variable.cpp.s

return_reference.o: return_reference.cpp.o
.PHONY : return_reference.o

# target to build an object file
return_reference.cpp.o:
	$(MAKE) -f CMakeFiles/return_reference.dir/build.make CMakeFiles/return_reference.dir/return_reference.cpp.o
.PHONY : return_reference.cpp.o

return_reference.i: return_reference.cpp.i
.PHONY : return_reference.i

# target to preprocess a source file
return_reference.cpp.i:
	$(MAKE) -f CMakeFiles/return_reference.dir/build.make CMakeFiles/return_reference.dir/return_reference.cpp.i
.PHONY : return_reference.cpp.i

return_reference.s: return_reference.cpp.s
.PHONY : return_reference.s

# target to generate assembly for a file
return_reference.cpp.s:
	$(MAKE) -f CMakeFiles/return_reference.dir/build.make CMakeFiles/return_reference.dir/return_reference.cpp.s
.PHONY : return_reference.cpp.s

size.o: size.cpp.o
.PHONY : size.o

# target to build an object file
size.cpp.o:
	$(MAKE) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/size.cpp.o
.PHONY : size.cpp.o

size.i: size.cpp.i
.PHONY : size.i

# target to preprocess a source file
size.cpp.i:
	$(MAKE) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/size.cpp.i
.PHONY : size.cpp.i

size.s: size.cpp.s
.PHONY : size.s

# target to generate assembly for a file
size.cpp.s:
	$(MAKE) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/size.cpp.s
.PHONY : size.cpp.s

string.o: string.cpp.o
.PHONY : string.o

# target to build an object file
string.cpp.o:
	$(MAKE) -f CMakeFiles/str.dir/build.make CMakeFiles/str.dir/string.cpp.o
.PHONY : string.cpp.o

string.i: string.cpp.i
.PHONY : string.i

# target to preprocess a source file
string.cpp.i:
	$(MAKE) -f CMakeFiles/str.dir/build.make CMakeFiles/str.dir/string.cpp.i
.PHONY : string.cpp.i

string.s: string.cpp.s
.PHONY : string.s

# target to generate assembly for a file
string.cpp.s:
	$(MAKE) -f CMakeFiles/str.dir/build.make CMakeFiles/str.dir/string.cpp.s
.PHONY : string.cpp.s

struct.o: struct.cpp.o
.PHONY : struct.o

# target to build an object file
struct.cpp.o:
	$(MAKE) -f CMakeFiles/struct.dir/build.make CMakeFiles/struct.dir/struct.cpp.o
.PHONY : struct.cpp.o

struct.i: struct.cpp.i
.PHONY : struct.i

# target to preprocess a source file
struct.cpp.i:
	$(MAKE) -f CMakeFiles/struct.dir/build.make CMakeFiles/struct.dir/struct.cpp.i
.PHONY : struct.cpp.i

struct.s: struct.cpp.s
.PHONY : struct.s

# target to generate assembly for a file
struct.cpp.s:
	$(MAKE) -f CMakeFiles/struct.dir/build.make CMakeFiles/struct.dir/struct.cpp.s
.PHONY : struct.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Array"
	@echo "... Namespace"
	@echo "... Random"
	@echo "... Trigon"
	@echo "... cbr"
	@echo "... class"
	@echo "... class_This"
	@echo "... default_value"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... return_reference"
	@echo "... size"
	@echo "... str"
	@echo "... struct"
	@echo "... Array.o"
	@echo "... Array.i"
	@echo "... Array.s"
	@echo "... Call_by_reference.o"
	@echo "... Call_by_reference.i"
	@echo "... Call_by_reference.s"
	@echo "... Class.o"
	@echo "... Class.i"
	@echo "... Class.s"
	@echo "... ClassWithThisPointer.o"
	@echo "... ClassWithThisPointer.i"
	@echo "... ClassWithThisPointer.s"
	@echo "... Namespace.o"
	@echo "... Namespace.i"
	@echo "... Namespace.s"
	@echo "... Random.o"
	@echo "... Random.i"
	@echo "... Random.s"
	@echo "... Trigonometry.o"
	@echo "... Trigonometry.i"
	@echo "... Trigonometry.s"
	@echo "... default_function_value_variable.o"
	@echo "... default_function_value_variable.i"
	@echo "... default_function_value_variable.s"
	@echo "... return_reference.o"
	@echo "... return_reference.i"
	@echo "... return_reference.s"
	@echo "... size.o"
	@echo "... size.i"
	@echo "... size.s"
	@echo "... string.o"
	@echo "... string.i"
	@echo "... string.s"
	@echo "... struct.o"
	@echo "... struct.i"
	@echo "... struct.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

